### ISSUE TITLE
我验得他妈已经想爆粗口了

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/account#20]
## 登出
<img width="1648" alt="image" src="https://github.com/user-attachments/assets/7d6f043a-34e4-41fd-98c5-a876781fc766">

你到底都测了啥？？

--------
**哎呀，要更新组件库的啦**

- [x] 已完成

**Comment by iRuxu** [comment]
## 找回密码

<img width="743" alt="image" src="https://github.com/user-attachments/assets/2387f9f0-e85d-452b-8522-2c20bc53382f">

- [x] 已完成

**Comment by Kaviilee** [comment]
> ## 登出
> <img alt="image" width="1648" src="https://private-user-images.githubusercontent.com/8476969/356908511-7d6f043a-34e4-41fd-98c5-a876781fc766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTcwNDIsIm5iZiI6MTcyMzQ1Njc0MiwicGF0aCI6Ii84NDc2OTY5LzM1NjkwODUxMS03ZDZmMDQzYS0zNGU0LTQxZmQtOThjNS1hODc2NzgxZmM3NjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMDk1OTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI0M2UxYjgyNmFhOWM1ZjZiYmQ3ZDc5NWUwMWE5ZGU4NjdhNmM2ZTg0YjY3ZjA4ZjRkZmFkMjdjNGNiNGI2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jvkSvAi9CQ4C4IsmoC5EeaiU8r0yvWoXR4rhkSYOqoY">
> 
> 你到底都测了啥？？
> 
>     * [ ]  已完成

你没有更新公共库 `npm install`
